//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpoolApi.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarpoolApi.Service.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Area code cannot be blank..
        /// </summary>
        public static string MissingAreaCode {
            get {
                return ResourceManager.GetString("MissingAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: City cannot be blank..
        /// </summary>
        public static string MissingCity {
            get {
                return ResourceManager.GetString("MissingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Email cannot be blank..
        /// </summary>
        public static string MissingEmail {
            get {
                return ResourceManager.GetString("MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: First name cannot be blank..
        /// </summary>
        public static string MissingFirstName {
            get {
                return ResourceManager.GetString("MissingFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Last name cannot be blank..
        /// </summary>
        public static string MissingLastName {
            get {
                return ResourceManager.GetString("MissingLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Password cannot be blank..
        /// </summary>
        public static string MissingPassword {
            get {
                return ResourceManager.GetString("MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Phone number cannot be blank..
        /// </summary>
        public static string MissingPhoneNumber {
            get {
                return ResourceManager.GetString("MissingPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: State cannot be blank..
        /// </summary>
        public static string MissingState {
            get {
                return ResourceManager.GetString("MissingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Street number cannot be blank..
        /// </summary>
        public static string MissingStreetNumber {
            get {
                return ResourceManager.GetString("MissingStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Zipcode cannot be blank..
        /// </summary>
        public static string MissingZipCode {
            get {
                return ResourceManager.GetString("MissingZipCode", resourceCulture);
            }
        }
    }
}
